// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEm4rCBxEcUsxtyz0jTmu7nPSlLzB680',
    appId: '1:266238614444:web:cebde78bcfe5dc0651b809',
    messagingSenderId: '266238614444',
    projectId: 'notiappitss2',
    authDomain: 'notiappitss2.firebaseapp.com',
    databaseURL: 'https://notiappitss2-default-rtdb.firebaseio.com',
    storageBucket: 'notiappitss2.appspot.com',
    measurementId: 'G-50P94P4J9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzwWECgp1XZe9KsyWqcXuaRvDzGUZm1M',
    appId: '1:266238614444:android:96b52a1d6548652251b809',
    messagingSenderId: '266238614444',
    projectId: 'notiappitss2',
    databaseURL: 'https://notiappitss2-default-rtdb.firebaseio.com',
    storageBucket: 'notiappitss2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP70dVRg9WMEblhNZQ4rcditffpRTA9Aw',
    appId: '1:266238614444:ios:3b29f4bd88ad3f0051b809',
    messagingSenderId: '266238614444',
    projectId: 'notiappitss2',
    databaseURL: 'https://notiappitss2-default-rtdb.firebaseio.com',
    storageBucket: 'notiappitss2.appspot.com',
    iosBundleId: 'com.example.notiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP70dVRg9WMEblhNZQ4rcditffpRTA9Aw',
    appId: '1:266238614444:ios:3b29f4bd88ad3f0051b809',
    messagingSenderId: '266238614444',
    projectId: 'notiappitss2',
    databaseURL: 'https://notiappitss2-default-rtdb.firebaseio.com',
    storageBucket: 'notiappitss2.appspot.com',
    iosBundleId: 'com.example.notiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuEm4rCBxEcUsxtyz0jTmu7nPSlLzB680',
    appId: '1:266238614444:web:5ef8aec75e5c6eb351b809',
    messagingSenderId: '266238614444',
    projectId: 'notiappitss2',
    authDomain: 'notiappitss2.firebaseapp.com',
    databaseURL: 'https://notiappitss2-default-rtdb.firebaseio.com',
    storageBucket: 'notiappitss2.appspot.com',
    measurementId: 'G-C3R0HFHNX4',
  );
}
