// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
/*
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
 );
*/

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTKCwJHk7vRYFzgEoFcsFagj-GUMbadg',
    appId: '1:518820698866:web:63238d4133488e89048e6b',
    messagingSenderId: '518820698866',
    projectId: 'itssnihongo2-8d63d',
    authDomain: 'itssnihongo2-8d63d.firebaseapp.com',
    storageBucket: 'itssnihongo2-8d63d.appspot.com',
    measurementId: 'G-864X3ZTJDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFTX-jCXXNHXCF-6ZNPq9tohpyub410Q',
    appId: '1:518820698866:android:a411048dc6a1aa05048e6b',
    messagingSenderId: '518820698866',
    projectId: 'itssnihongo2-8d63d',
    storageBucket: 'itssnihongo2-8d63d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1TUvQYgEbA1o0GtvB6ryHlaNrI1Yom8',
    appId: '1:518820698866:ios:60a020fcb3d32769048e6b',
    messagingSenderId: '518820698866',
    projectId: 'itssnihongo2-8d63d',
    storageBucket: 'itssnihongo2-8d63d.appspot.com',
    iosBundleId: 'com.example.notiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF1TUvQYgEbA1o0GtvB6ryHlaNrI1Yom8',
    appId: '1:518820698866:ios:60a020fcb3d32769048e6b',
    messagingSenderId: '518820698866',
    projectId: 'itssnihongo2-8d63d',
    storageBucket: 'itssnihongo2-8d63d.appspot.com',
    iosBundleId: 'com.example.notiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDTKCwJHk7vRYFzgEoFcsFagj-GUMbadg',
    appId: '1:518820698866:web:2ce567d5f758346a048e6b',
    messagingSenderId: '518820698866',
    projectId: 'itssnihongo2-8d63d',
    authDomain: 'itssnihongo2-8d63d.firebaseapp.com',
    storageBucket: 'itssnihongo2-8d63d.appspot.com',
    measurementId: 'G-F6K9MJLSJK',
  );
}
